# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.CharField(db_index=True, default=datetime.datetime(2016, 1, 2, 13, 30, 27, 988472, tzinfo=utc), max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
