# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_tags',
            field=models.CharField(default=datetime.datetime(2016, 1, 1, 19, 3, 56, 419516, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
