# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
