# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160101_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=16)),
                ('project_name', models.CharField(max_length=150)),
            ],
        ),
    ]
