# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin and beyongsite.', verbose_name='admin status'),
        ),
    ]
