# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
